apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana # Use the namespace created in step 1 (if applicable)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest # You can specify a specific version if needed
          ports:
            - containerPort: 3000
          env:
            - name: GF_INSTALL_PLUGINS
              value: "grafana-piechart-panel,grafana-clock-panel" # Optional, specify additional plugins here
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana
#   namespace: grafana # Use the namespace created in step 1 (if applicable)
# spec:
#   ports:
#     - port: 80
#       targetPort: 3000
#   selector:
#     app: grafana

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana-nodeport
#   namespace: grafana # Use the namespace created in step 1 (if applicable)
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 3000
#   selector:
#     app: grafana

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
  namespace: grafana # Use the namespace created in step 1 (if applicable)
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: grafana