apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-kafka-credentials
  namespace: default
spec:
  secretTargetRef:
    - parameter: username
      name: api-secrets
      key: P5JKLIIC3H47AN7E
    - parameter: password
      name: api-secrets
      key: mEMURM0XLWPeolc09cfUqd4rUZQrjMTzR22FpIav5lEFCwsVAzY65lKW7idPyghQ